### PR TITLE
Added support for webpacker

### PR DESCRIPTION
**Pull request by puneet-sutar**
This is PR to support rails projects with  [Webpacker](https://github.com/rails/webpacker) for rails >= v5.0. Webpacker + yarn would be built into rails 5.1.

If you guys are intrested in merging then I would go ahead an add testcases. Would really appreciate  if you can let me know the bare minimum things(i am not sure about what and how to test the package.json and yarn.lock related stuff) that should be tested.

Things Done:

- Renamed bin/compile to compile.rb and added bash script in compile to update path(cannot update path from ruby code) to include vender/node and vendor/yarn directories and execute compile.rb.
- Added logic to detect presense of yarn.lock and package.json.
- If above files are present then identify the version of node and yarn and download the tars and untar them to ./vendor.
- Install the node_modules using `bin/yarn install`
- Run rake webpacker:complile if the task is present.

### CODE REVIEW

**Comment by harrikauhanen** [comment]
This needs a bit more work. `rake webpacker:compile` must be run before `rake assets:precompile`. Also, we need `bin/yarn` before webpacker.

I had a quick look on buildback and noticed assets precompiling is a task of **ruby** language pack https://github.com/heroku/heroku-buildpack-ruby/blob/master/lib/language_pack/ruby.rb#L106 This already feels wrong to me as it should be a Rails task. For the webpacker, the task is executed way too early. I got my app working by commenting out `run_assets_precompile_rake_task` https://github.com/harrikauhanen/heroku-buildpack-ruby/commit/ffd5215a4cc5853c6dba00df56d3d51f4cfb9522 and running assets precompilation in rails5 language pack https://github.com/harrikauhanen/heroku-buildpack-ruby/commit/4b8804e414eb1462f7c54dbea0223ba9fec95d73, and only after webpacker.

This solution is not mergeable the official buildback as we effectively broke asset precompilation on older Rails version, and we no longer try to detect the need for compilation (sniffing the existence of manifest files).

**Comment by swrobel** [comment]
@puneet-sutar please fix the merge conflicts on your branch!

@harrikauhanen please merge!

**Comment by puneet-sutar** [comment]
@swrobel My bad missed out on harrikauhanen's message. Will try and do the changes this week.

**Comment by puneet-sutar** [comment]
@swrobel Work on this would be redundant after https://github.com/rails/webpacker/pull/101 has been merged. 

cc @harrikauhanen 

Just closing the PR for now.

**Comment by swrobel** [comment]
@puneet-sutar thanks for the update! It still seems that more custom code is required beyond just adding the nodejs buildpack, correct? For example, `rake webpacker:compile` still has to run before `rake assets:precompile`.

**Comment by puneet-sutar** [comment]
@swrobel rake webpacker:compile is no more required to be run separately.
https://github.com/rails/webpacker/issues/45#issuecomment-273184376
https://github.com/rails/webpacker/commit/d2a6537e6ab0896a9bf14b6eddc5c0961db2c802

**Pull request closed without merging**
