### PR TITLE
Bundler 1.17.2

### PR DESCRIPTION
**Pull request by schneems**

### CODE REVIEW

**Comment by jaredbeck** [comment]
After this week's [security patches to rubygems](https://blog.rubygems.org/2019/03/05/security-advisories-2019-03.html) it is becoming increasingly difficult to run bundler 1.15 locally. My team can't figure it out and we are now running bundler 1.17 locally which is obviously not ideal for dev/prod parity. We get this legitimate warning when we deploy:

> remote:        Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.17.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.

Does heroku have any recently updated documentation explaining how to run 1.15 locally?

**Comment by schneems** [comment]
You can upgrade to bundler 2.0.1 and be running the exact same version of bundler that's on the platform right now.

The issue with this PR is that 1.16 made a backwards breaking change that we're having to re-compile jruby to work around.

I would have more time to work on it, however, the bundler 2 release has been demanding a significant amount of my available time. The good news is you can use that to skip bundler 1.17 and jump straight to bundler 2.

> After this week's security patches to rubygems it is becoming increasingly difficult to run bundler 1.15 locally. 

What does a RubyGem security release have to do with bundler?

**Comment by jaredbeck** [comment]
> The good news is you can use that to skip bundler 1.17 and jump straight to bundler 2.

I'll try that, thanks.

> What does a RubyGem security release have to do with bundler?

The recommended fix `gem update --system` updates bundler, and I couldn't figure out how downgrade back to 1.15.

**Comment by schneems** [comment]
That's quite surprising, but I was able to reproduce this behavior in a docker image. I opened a ticket with rubygems about the behavior https://github.com/rubygems/rubygems/issues/2671.

**Comment by schneems** [comment]
Closing, in favor of 1.17.3 https://github.com/heroku/heroku-buildpack-ruby/pull/845

**Comment by jaredbeck** [comment]
> The good news is you can use that to skip bundler 1.17 and jump straight to bundler 2.

Worked for me, thanks.

```
remote:        Your app was upgraded to bundler 2.0.1.
remote:        Previously you had a successful deploy with bundler 1.15.2.
...
remote: -----> Installing dependencies using bundler 2.0.1
...
remote:        Removing bundler (1.15.2)
```

It's been a struggle for my team to use 1.15 for the past year, as the rest of the ruby community moved on, so I'm glad to see this is finally resolved. While I'm frustrated it took so long for heroku to upgrade, I appreciate your patient customer service throughout.

**Comment by schneems** [comment]
> It's been a struggle for my team to use 1.15 for the past year

Have you seen an inconsistency between the behavior of bundler 1.x locally and on Heroku before? I don't think there's any need to artificially only follow the patch level of bundler that Heroku is using. I've not found any Gemfile.lock by any version of bundler 1.x that's incompatible with bundler 1.15.2.

**Comment by LeZuse** [comment]
@schneems We've been actually running 1.17.3 on our dev machines for some time now as well and haven't run into any issues.

**Pull request closed without merging**
