### PR TITLE
Bundler 1.15.0

### PR DESCRIPTION
**Pull request by schneems**
Bundler fixed this bug https://github.com/bundler/bundler/pull/5388 which causes this issue https://github.com/ruby/openssl/issues/103. To be able to deploy Ruby 2.4 and the openssl gem on Heroku.

### CODE REVIEW

**Comment by andremedeiros** [comment]
@hone is there anything we can do to help speed up merging this PR?

**Comment by andremedeiros** [comment]
@schneems @hone thank you! I owe you two big 🍺

**Comment by schneems** [comment]
We will leave on master until next week. If no reported problems we can deploy.

**Comment by schneems** [comment]
We are going to revert 1.15.0 it is not stable enough https://github.com/heroku/heroku-buildpack-ruby/pull/580

**Pull request merged**
