### PR TITLE
Use HTTPS for interactions with GitHub and S3

### LINKED ISSUE #589: Rakefile tasks interact with GitHub and S3 over HTTP
Several of the Rakefile tasks either clone from GitHub, or upload to S3 (via the `support/s3/s3` tool) over HTTP:
https://github.com/heroku/heroku-buildpack-ruby/blob/1ff2d31a2b1d9428e69d2add408f720774a9809e/Rakefile#L61-L63
https://github.com/heroku/heroku-buildpack-ruby/blob/ce11aca649273103dfeed0ccc5880858be116aa6/support/s3/s3#L153-L154

Valid SSL certificates are served for all of the domains in question, so should be accessed over HTTPS instead.

### PR DESCRIPTION
**Pull request by edmorley**
Fixes #589.

### CODE REVIEW

**Comment by edmorley** [comment]
The Travis run failed for an unrelated reason (PRs from forks do not have access to secure Travis environment variables, see also: heroku/heroku-buildpack-clojure#52, heroku/heroku-buildpack-jvm-common#28).

**Comment by edmorley** [comment]
@hone I don't suppose you could take a look at this and #588? :-)

**Comment by schneems** [comment]
Thanks. I'll try to merge tomorrow morning so I can babysit any potential failures, but this should be fairly safe.

**Comment by edmorley** [comment]
Merged via #603 so Travis could run.

Many thanks!

**Pull request closed without merging**
