### PR TITLE
Upgrade bundler to 1.11.2

### PR DESCRIPTION
**Pull request by dmathieu**

### CODE REVIEW

**Comment by schneems** [comment]
WFM https://peaceful-fjord-29502.herokuapp.com/ going to merge and keep on master for awhile

**Comment by discorick** [comment]
I think this got deployed, having deployment failures because of 1.11.2

**Comment by schneems** [comment]
This isn't deployed, your app is likely using master. Can you open a support ticket help.heroku.com

**Comment by schneems** [comment]
@discorick did you open a support ticket? What is the ticket number?

**Comment by discorick** [comment]
Hey @schneems, yes we deploy with master.

I opened up a ticket on help.heroku.com to document what I experienced and how I fixed it. Ticket #338768

**Comment by schneems** [comment]
I started a doc to describe our policy with bundler and how to use an older release that might be of some help. I know you already got your problem working, would you mind looking over https://devcenter.heroku.com/articles/bundler-version and giving feedback if you have time?

**Pull request merged**
