### PR TITLE
Update readme with banner image. 

### PR DESCRIPTION
**Pull request by mattgraham**
Creating images for all the Heroku official buildpacks. Thoughts on this?

### CODE REVIEW

**Comment by hone** [comment]
:+1:

**Comment by mattgraham** [comment]
Updated, already...
ruby

**Comment by mathias** [comment]
Any ideas why this failed? The build log is awfully noisy and I'm not familiar with this test suite.

**Comment by mattgraham** [comment]
@hone ^^

**Comment by schneems** [comment]
I think your branch doesn't live on heroku/heroku-buildpack-ruby so Travis won't run tests with the encrypted env vars as a security measure (otherwise you could submit a PR that is just `puts ENV` to grab all our secrets. This is a cosmetic change you can either [ci skip] it or merge in as is. Thanks for the work, looks great. :+1:

**Pull request merged**
