### PR TITLE
Instruct curl to follow redirects.

### PR DESCRIPTION
**Pull request by schneems**

### CODE REVIEW

**Comment by brixen** [comment]
Are these spec failures related to my change?

**Comment by schneems** [comment]
re-running

**Comment by parkr** [comment]
The last run on `master` occurred [a month ago and is passing](https://travis-ci.org/heroku/heroku-buildpack-ruby/builds/91878088).

**Comment by schneems** [comment]
That same test is failing on master. Everything else is passing. Merging in.

**Comment by brixen** [comment]
Thanks @schneems!

**Pull request merged**
