### PR TITLE
Added a JRuby specific error message if version is not found

### PR DESCRIPTION
**Pull request by jkutner**
I tried spliting this up so that the common parts were only in code once, and not repeated like this... but honestly it just became a mess.  So i think it might be better just to duplicate the message like this.

### CODE REVIEW

**Comment by schneems** [comment]
Tests

```
body: "No such stack.
```

ಠ_ಠ

I swear, I spend 2x the amount of time fixing random errors like this than fixing bugs on the buildpack

**Comment by schneems** [comment]
I'm :+1:  on this. Any thoughts @hone ?

**Comment by hone** [comment]
:+1: 

For that error message, is it now `cedar-10`?

**Comment by hone** [comment]
Build now [passes](https://travis-ci.org/heroku/heroku-buildpack-ruby) and merged with 8150fb62ca6c24100fcccc54cc5240e09dd8a1c0

**Pull request closed without merging**
