### PR TITLE
Use shell in Detect for speed

### LINKED ISSUE #368: Re-write detect to remove ruby for speed
While it doesn't matter that much for the speed of an individual build, Ruby detect gets executed for EVERY build on the platform that doesn't specify an explicit buildpack. Looks like we could speed this up by using shell or bash:

https://github.com/heroku/heroku-buildpack-ruby/commit/dd75ed563577e305bead895d21c56e704f70d307#commitcomment-10919871

### PR DESCRIPTION
**Pull request by DyegoCosta**
Resolves #368

```shell
# ruby
$ ( for i in {1..1000}; do; bin/detect /ruby-app; done; )  29.98s user 6.32s system 97% cpu 37.266 total

# sh
$ ( for i in {1..1000}; do; bin/detect /ruby-app; done; )  1.32s user 1.43s system 98% cpu 2.789 total
```

### CODE REVIEW

**Comment by schneems** [comment]
Thanks! I'm running tests on #374 so that travis can execute with env vars. When it passes, i'll merge

**Comment by DyegoCosta** [comment]
@schneems Awesome
I see the build failed, is the error related to this patch? If there is something I can fix let me know

**Comment by schneems** [comment]
It's a rate limiting issue with the test account, I need to fix it.



—

**Comment by hone** [comment]
Thanks for the patch!

**Pull request merged**
