### PR TITLE
Hardcoded nodebin

### PR DESCRIPTION
**Pull request by schneems**
Hardcoding nodebin results so we can ship before security review. Commits from @hone from #540

### CODE REVIEW

**Comment by hone** [comment]
@schneems we should use s3pository instead of s3 directly

**Comment by hunterloftis** [comment]
nodebin will be done w/ security review late next week. After that I'd just ask @jmorrell when any remediations are finished.

**Comment by schneems** [comment]
Tests are green

**Comment by josegonzalez** [comment]
Has nodebin passed security review? If so, using it to have a single source of truth for nodejs would be awesome.

**Pull request merged**
