### PR TITLE
Don't write database.yml if using ActiveRecord >= 4.1

### PR DESCRIPTION
**Pull request by damonmorgan**
Patch for https://github.com/heroku/heroku-buildpack-ruby/issues/364

An example app for testing can be found at https://github.com/damonmorgan/activerecord41_scaffold

### CODE REVIEW

**Comment by hone** [comment]
We created an empty method in Rails41 class so it wouldn't. I believe your patch actually undoes that work since pre 4.1, we create a database.yml.

**Comment by damonmorgan** [comment]
Yes, but that should be redundant code now as [this change](https://github.com/heroku/heroku-buildpack-ruby/pull/403/files#diff-3fc66e13e389ff4d15c7ca3ddb86464eR632) should mean that any application using ActiveRecord 4.1+ (including Rails 4.1+, but not limited to only Rails now) shouldn't have the database.yml file written now? I left the tests in for Rails 4.1 so they should still pass.

**Comment by schneems** [comment]
Tests are now passing over at https://github.com/heroku/heroku-buildpack-ruby/pull/404

I modified it to preserve the accidental functionality we had that would write a config/database.yml before when you don't have activerecord. We can consider killing that later, but It is easier to be backwards compatible than to deal with broken apps in support tickets for now.

**Comment by schneems** [comment]
merged in #404. It will live on master for awhile to see if there are any problems/regressions before it gets deployed. Thanks for the help :heart:

**Comment by damonmorgan** [comment]
Thanks

**Pull request closed without merging**
