### PR TITLE
Remove ctrl+C message

### PR DESCRIPTION
**Pull request by cyx**
We're proposing to remove supporting the behavior moving
forward.

### CODE REVIEW

**Comment by schneems** [comment]
Heroku won't be removing CTRL+C to cancel builds.

**Comment by schneems** [comment]
To add some context here. The CTRL+C option isn't fully supported across HTTP git so if you're using that, the message is incorrect as CTRL+C won't stop your deploy. This is bad since we're explicitly saying that it will. The Build and Packaging team plans on removing the ability to CTRL+C from SSH git builds soon, removing this message would reflect current status of builds.

**Comment by cyx** [comment]
^ bump :)

**Comment by schneems** [comment]
We need to modify the rake task detection logic so this will show up less. That can happen sometime after railsconf

**Pull request merged**
